"""Agent persona / roster export — the *participants* surface.

Every prior share surface on a published sim describes what the swarm
*concluded* (``signal.json``, ``polymarket.json``, ``volatility``) or
how its belief *evolved* (``chart.svg``, ``peak-round``, ``agents/sparklines``,
``trajectory.csv``). None of them describe **who was in the debate** in a
machine-readable form. ``transcript.md`` has the names, bios, and personas
embedded as Markdown headings; a researcher comparing agent-pool
composition across runs — *"did the financial-analyst-heavy sim converge
faster than the retail-trader-heavy one?"* — had to regex through the
Markdown.

This module fills that gap with one stdlib derivation:

  {
    "schema_version": "1",
    "simulation_id":  "<echoed>",
    "scenario_preview": "<200-char truncated scenario>",
    "agent_count":    <int>,
    "has_trajectory_data": <bool>,
    "agents": [
      {
        "agent_id":          <int>,
        "username":          <str>,
        "name":              <str>,
        "bio":               <str>,
        "persona_preview":   <str — persona truncated to 280 chars>,
        "age":               <int|null>,
        "gender":            <str|null>,
        "mbti":              <str|null>,
        "country":           <str|null>,
        "profession":        <str|null>,
        "interested_topics": [<str>...],
        "karma":             <int>,
        "created_at":        <str>,
        "final_stance":      "bullish" | "neutral" | "bearish",
        "final_position":    <float|null>,
        "rounds_participated": <int>,
      },
      ...
    ]
  }

Design notes
------------

* **Reuses ``reddit_profiles.json`` (+ ``polymarket_profiles.json``).**
  Same lookup the transcript renderer and agent_sparklines_service use,
  so an agent's name + bio + persona match across every surface that
  exposes them. First write wins; reddit_profiles takes precedence.

* **Reuses ``trajectory.json`` for the belief layer.** ``final_stance``,
  ``final_position`` and ``rounds_participated`` come from
  ``load_agent_trajectories`` in ``agent_sparklines_service`` so the
  ±0.2 threshold + ``_avg_position`` mean stay in lockstep. Two
  surfaces, one belief-bucketing rule. An agent with no belief data in
  any round (a profile-only sim, or a pre-rounds export) still appears
  in the roster but with ``final_stance=neutral``,
  ``final_position=null``, ``rounds_participated=0`` — the participant
  surface answers *who was here*, not *did they say anything*.

* **Persona is previewed, not dumped.** The full ``persona`` field is
  often 1–2 KB of generated prose; a research script pulling 50 agents
  doesn't want 100 KB of LLM text. ``persona_preview`` is truncated to
  280 chars (one tweet-worth of context); the full text remains in
  ``transcript.md`` for callers who need it.

* **Roster order is most-bullish-first by final position.** Ties broken
  by ``agent_id`` ascending so the order is deterministic across calls.
  Matches the agent_sparklines ordering so a UI rendering both surfaces
  side-by-side aligns row-for-row. Agents with no belief data
  (``final_position=None``) sort last in ``agent_id`` order so they
  don't dominate the top of the roster.

* **Pure stdlib.** ``json`` + ``os``. Same dependency posture as every
  other export module — keeps the platform on its zero-new-deps streak.

* **Publish-gated by the route handler.** This module assembles the
  payload; the ``is_public`` gate lives in ``simulation.py`` where every
  other share surface enforces it.
"""

from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

from . import agent_sparklines_service


SCHEMA_VERSION = "1"

# Persona prose is generated by the LLM and routinely runs 1–2 KB per
# agent. The transcript already carries the full text; this surface
# previews it so a programmatic consumer scanning 50 agents stays under
# a tractable payload size. 280 chars matches the tweet-thread + scenario
# preview cadence the rest of the codebase uses.
PERSONA_PREVIEW_CHARS = 280

# Bio is generally short (one-line); cap defensively in case an operator
# hand-edits a profile with multi-paragraph bio text.
BIO_PREVIEW_CHARS = 280

# Scenario echoed at the envelope level so a downstream tool can render a
# one-line "roster of sim <X> on scenario <Y>" line without a second
# round-trip to embed-summary. Matches the clone_service truncation cap.
SCENARIO_PREVIEW_CHARS = 200

# Same ±0.2 stance threshold the embed-summary, share card, transcript,
# trajectory.csv, chart.svg, peak-round, volatility, and sparklines
# surfaces all use.
STANCE_THRESHOLD = 0.2


# ── On-disk readers ────────────────────────────────────────────────────────


def _safe_load_json(path: str) -> Any:
    """Read JSON, returning ``None`` on missing / corrupt input.

    Never raises — the route handler must resolve a malformed artifact to
    a clean 404 ("no data yet"), never a 500.
    """
    if not path or not os.path.exists(path):
        return None
    try:
        with open(path, "r", encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:
        return None


def _load_profiles(sim_dir: str) -> List[Dict[str, Any]]:
    """Load the agent roster — reddit_profiles.json first, then polymarket.

    Returns a list keyed by ``user_id`` order of first appearance. Each
    entry is a copy of the on-disk dict so a downstream consumer mutating
    the returned list can't poison the cached read. Reddit profile takes
    precedence on duplicate ``user_id`` so the persona surface matches
    the transcript renderer's choice.
    """
    seen_ids: set[int] = set()
    out: List[Dict[str, Any]] = []
    for filename in ("reddit_profiles.json", "polymarket_profiles.json"):
        data = _safe_load_json(os.path.join(sim_dir or "", filename))
        if not isinstance(data, list):
            continue
        for row in data:
            if not isinstance(row, dict):
                continue
            try:
                uid = int(row.get("user_id"))
            except (TypeError, ValueError):
                continue
            if uid in seen_ids:
                continue
            seen_ids.add(uid)
            out.append(dict(row))
    return out


# ── Field normalisers ──────────────────────────────────────────────────────


def _truncate(text: Any, limit: int) -> str:
    """Coerce to str, strip, and truncate with a trailing ellipsis."""
    if text is None:
        return ""
    s = str(text).strip()
    if len(s) <= limit:
        return s
    return s[: max(1, limit - 1)].rstrip() + "…"


def _safe_str(value: Any) -> str:
    """Stripped string; ``None`` ⇒ empty."""
    if value is None:
        return ""
    try:
        return str(value).strip()
    except Exception:
        return ""


def _optional_str(value: Any) -> Optional[str]:
    """Stripped string or ``None`` when empty — preserves null vs blank
    distinction the JSON consumer expects."""
    s = _safe_str(value)
    return s or None


def _optional_int(value: Any) -> Optional[int]:
    """Int or ``None`` when missing / unparseable."""
    if value is None:
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def _safe_int(value: Any, default: int = 0) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _normalize_topics(value: Any) -> List[str]:
    """Coerce ``interested_topics`` to a list of trimmed strings.

    Drops empty entries and de-duplicates while preserving order so a
    consumer iterating the list never sees ``""`` or repeated tags.
    Non-list inputs degrade to an empty list rather than raising.
    """
    if not isinstance(value, list):
        return []
    seen: set[str] = set()
    out: List[str] = []
    for item in value:
        s = _safe_str(item)
        if not s or s in seen:
            continue
        seen.add(s)
        out.append(s)
    return out


def _classify_stance(value: float) -> str:
    """Bucket a continuous belief position into bullish/neutral/bearish."""
    try:
        v = float(value)
    except (TypeError, ValueError):
        return "neutral"
    if v > STANCE_THRESHOLD:
        return "bullish"
    if v < -STANCE_THRESHOLD:
        return "bearish"
    return "neutral"


# ── Belief layer ──────────────────────────────────────────────────────────


def _load_belief_layer(sim_dir: str) -> Dict[int, Dict[str, Any]]:
    """Map ``agent_id → {final_position, rounds_participated, final_stance}``.

    Reuses ``agent_sparklines_service.load_agent_trajectories`` so the
    per-agent scalar (``_avg_position`` mean) and the ±0.2 stance
    bucketing match every other surface byte-for-byte. Agents that never
    held a usable position simply don't appear here; the caller fills in
    defaults (``final_stance=neutral``, ``final_position=None``,
    ``rounds_participated=0``) so the participant surface still lists
    them.
    """
    trajectories = agent_sparklines_service.load_agent_trajectories(sim_dir)
    out: Dict[int, Dict[str, Any]] = {}
    for entry in trajectories:
        points = entry.get("trajectory") or []
        if not points:
            continue
        last = points[-1]
        try:
            final_pos = float(last.get("position"))
        except (TypeError, ValueError):
            continue
        out[int(entry["agent_id"])] = {
            "final_position": round(final_pos, 3),
            "rounds_participated": len(points),
            "final_stance": _classify_stance(final_pos),
        }
    return out


# ── Scenario echo ──────────────────────────────────────────────────────────


def _load_scenario_preview(sim_dir: str) -> str:
    """Read ``simulation_requirement`` from ``simulation_config.json``.

    Empty string when the config is missing or doesn't carry the field —
    same posture as ``clone_service._load_config``. Truncated to 200
    chars with a trailing ellipsis when over the limit.
    """
    cfg = _safe_load_json(os.path.join(sim_dir or "", "simulation_config.json"))
    if not isinstance(cfg, dict):
        return ""
    return _truncate(cfg.get("simulation_requirement"), SCENARIO_PREVIEW_CHARS)


# ── Per-agent assembly ─────────────────────────────────────────────────────


def _build_agent_entry(
    profile: Dict[str, Any],
    belief: Dict[int, Dict[str, Any]],
) -> Optional[Dict[str, Any]]:
    """Compose one agent's roster entry from its profile dict + belief map.

    Returns ``None`` for profiles missing a usable ``user_id`` so the
    caller can skip them rather than raising. Every other field falls
    back to a typed default (empty string, empty list, ``None``,
    ``"neutral"``) so the JSON consumer sees a fixed key set across
    agents regardless of which optional persona fields the profile
    generator populated.
    """
    try:
        agent_id = int(profile.get("user_id"))
    except (TypeError, ValueError):
        return None

    username = _safe_str(profile.get("username")) or _safe_str(profile.get("user_name"))
    name = _safe_str(profile.get("name")) or username or f"Agent {agent_id}"

    belief_row = belief.get(agent_id)
    if belief_row:
        final_position = belief_row["final_position"]
        rounds_participated = belief_row["rounds_participated"]
        final_stance = belief_row["final_stance"]
    else:
        final_position = None
        rounds_participated = 0
        final_stance = "neutral"

    return {
        "agent_id": agent_id,
        "username": username,
        "name": name,
        "bio": _truncate(profile.get("bio"), BIO_PREVIEW_CHARS),
        "persona_preview": _truncate(profile.get("persona"), PERSONA_PREVIEW_CHARS),
        "age": _optional_int(profile.get("age")),
        "gender": _optional_str(profile.get("gender")),
        "mbti": _optional_str(profile.get("mbti")),
        "country": _optional_str(profile.get("country")),
        "profession": _optional_str(profile.get("profession")),
        "interested_topics": _normalize_topics(profile.get("interested_topics")),
        "karma": _safe_int(profile.get("karma"), default=0),
        "created_at": _safe_str(profile.get("created_at")),
        "final_stance": final_stance,
        "final_position": final_position,
        "rounds_participated": rounds_participated,
    }


def _agent_sort_key(entry: Dict[str, Any]) -> tuple:
    """Sort key: most-bullish-first by final_position, ties on agent_id.

    Agents with no belief data (``final_position=None``) sort to the
    bottom — they're roster-only entries; placing them at the top would
    bury the participants who actually drove the consensus. Among the
    no-belief group, ties break on ``agent_id`` ascending so order is
    deterministic.
    """
    pos = entry.get("final_position")
    has_belief = pos is not None
    # Tuple sorts ascending; flip belief bucket so "has belief" comes
    # first (False < True → invert with `not`), then within the bucket
    # sort by descending position (negate for sort-ascending semantics).
    return (
        0 if has_belief else 1,
        -float(pos) if has_belief else 0.0,
        int(entry.get("agent_id") or 0),
    )


# ── Public entry point ────────────────────────────────────────────────────


def build_agent_export(
    simulation_id: str,
    sim_dir: str,
) -> Optional[Dict[str, Any]]:
    """Compose the agents.json envelope for a published sim.

    Reads ``reddit_profiles.json`` (then ``polymarket_profiles.json``)
    for the roster and ``trajectory.json`` for the belief layer. Returns
    ``None`` when no profile file produces a usable agent — the route
    handler translates that to a 404 ("not ready / no agent data") so a
    consumer can distinguish a not-ready sim from a private one (403).

    Args:
        simulation_id: Echoed in the response envelope. Validated by the
            route handler before this is invoked.
        sim_dir: Absolute path to the sim's data directory
            (``Config.WONDERWALL_SIMULATION_DATA_DIR / simulation_id``).

    Returns:
        The full envelope dict, or ``None`` when the sim has no profile
        data on disk yet.
    """
    profiles = _load_profiles(sim_dir)
    if not profiles:
        return None

    belief = _load_belief_layer(sim_dir)

    agents: List[Dict[str, Any]] = []
    for profile in profiles:
        entry = _build_agent_entry(profile, belief)
        if entry is None:
            continue
        agents.append(entry)

    if not agents:
        return None

    agents.sort(key=_agent_sort_key)

    has_trajectory_data = any(a["final_position"] is not None for a in agents)
    scenario_preview = _load_scenario_preview(sim_dir)

    return {
        "schema_version": SCHEMA_VERSION,
        "simulation_id": simulation_id,
        "scenario_preview": scenario_preview,
        "agent_count": len(agents),
        "has_trajectory_data": has_trajectory_data,
        "agents": agents,
    }
